<?php
/**
 * WooCommerce Support
 * Loads only when WooCommerce plugin is active.
 *
 * Template strategy
 * -----------------
 * - Templates that need bespoke Tailwind markup (e.g. notices, the review
 *   order table, the single-product image gallery) get a real file in
 *   /woocommerce/ — those go through the normal WC template loader.
 * - Stock markup we still inherit (form fields, quantity inputs, payment
 *   methods, the checkout loop start, the rating stars) gets Tailwind
 *   classes injected via the filters below, so the look stays consistent
 *   with the rest of the theme without overriding every template.
 *
 * Images
 * ------
 * The media-optimize helper blogpro_responsive_img() is the one source of
 * truth for rendering <img> in the theme — it emits WebP via the
 * /blogpro-img/ resizer with a 320/480/768/1024/1280/1600 srcset. The new
 * templates call it directly. For images that still come from stock WC
 * markup (e.g. the gallery main image, the product thumbnail <img>
 * generated by wc_get_gallery_image_html) the whole-page
 * blogpro_responsive_buffer_images() pass in media-optimize rewrites every
 * <img> to the resizer URL.
 */

if ( ! defined( 'ABSPATH' ) ) exit;

// Exit if WooCommerce is not active
if ( ! class_exists( 'WooCommerce' ) ) return;

/* ---------------------------------------------------------------
 * 1. Declare WooCommerce theme support
 * ------------------------------------------------------------- */
function blogpro_wcom_setup() {
    add_theme_support( 'wc-product-gallery-zoom' );
    add_theme_support( 'wc-product-gallery-lightbox' );
    add_theme_support( 'wc-product-gallery-slider' );
}
add_action( 'after_setup_theme', 'blogpro_wcom_setup' );

/* ---------------------------------------------------------------
 * 2. Remove WooCommerce default styles (use Tailwind instead)
 * ------------------------------------------------------------- */
add_filter( 'woocommerce_enqueue_styles', '__return_empty_array' );

/* ---------------------------------------------------------------
 * 3. Dequeue WC scripts on non-shop pages (performance)
 * ------------------------------------------------------------- */
function blogpro_wcom_dequeue_scripts() {
    if ( is_woocommerce() || is_cart() || is_checkout() || is_account_page() ) return;
    wp_dequeue_script( 'wc-cart-fragments' );
}
add_action( 'wp_enqueue_scripts', 'blogpro_wcom_dequeue_scripts', 100 );

/* ---------------------------------------------------------------
 * 4. Wrap WooCommerce content with our container
 *    Defer remove_action until after_setup_theme priority 11 so it
 *    runs AFTER WC's template-hooks registration (which is also
 *    bound to after_setup_theme at the default priority 10).
 * ------------------------------------------------------------- */
function blogpro_wcom_wrappers() {
    remove_action( 'woocommerce_before_main_content', 'woocommerce_output_content_wrapper', 10 );
    remove_action( 'woocommerce_after_main_content', 'woocommerce_output_content_wrapper_end', 10 );

    add_action( 'woocommerce_before_main_content', 'blogpro_wcom_wrapper_before' );
    add_action( 'woocommerce_after_main_content', 'blogpro_wcom_wrapper_after' );
}
add_action( 'after_setup_theme', 'blogpro_wcom_wrappers', 11 );

function blogpro_wcom_wrapper_before() {
    echo '<div class="w-full max-w-7xl mx-auto px-4 md:px-0 py-8">';
}
function blogpro_wcom_wrapper_after() {
    echo '</div>';
}

/* ---------------------------------------------------------------
 * 5. Cart icon in header
 * ------------------------------------------------------------- */
function blogpro_wcom_cart_icon() {
    if ( ! WC()->cart ) return;
    $count = WC()->cart->get_cart_contents_count();
    $url   = wc_get_cart_url();
    ?>
    <a href="<?php echo esc_url( $url ); ?>" class="relative text-gray-600 hover:text-indigo-600 transition-colors blogpro-cart-icon" aria-label="<?php esc_attr_e( 'View cart', 'blog-pro' ); ?>">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
        </svg>
        <?php if ( $count > 0 ) : ?>
            <span class="absolute -top-2 -right-2 bg-indigo-600 text-white text-xs font-bold rounded-full h-5 w-5 flex items-center justify-center">
                <?php echo esc_html( $count ); ?>
            </span>
        <?php endif; ?>
    </a>
    <?php
}

/* ---------------------------------------------------------------
 * 6. Fragment refresh: update cart count when items added/removed
 * ------------------------------------------------------------- */
function blogpro_wcom_cart_fragments( $fragments ) {
    $count = WC()->cart ? WC()->cart->get_cart_contents_count() : 0;
    ob_start();
    ?>
    <a href="<?php echo esc_url( wc_get_cart_url() ); ?>" class="relative text-gray-600 hover:text-indigo-600 transition-colors blogpro-cart-icon" aria-label="<?php esc_attr_e( 'View cart', 'blog-pro' ); ?>">
        <svg class="w-6 h-6" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M3 3h2l.4 2M7 13h10l4-8H5.4M7 13L5.4 5M7 13l-2.293 2.293c-.63.63-.184 1.707.707 1.707H17m0 0a2 2 0 100 4 2 2 0 000-4zm-8 2a2 2 0 11-4 0 2 2 0 014 0z"/>
        </svg>
        <?php if ( $count > 0 ) : ?>
            <span class="absolute -top-2 -right-2 bg-indigo-600 text-white text-xs font-bold rounded-full h-5 w-5 flex items-center justify-center">
                <?php echo esc_html( $count ); ?>
            </span>
        <?php endif; ?>
    </a>
    <?php
    $fragments['.blogpro-cart-icon'] = ob_get_clean();
    return $fragments;
}
add_filter( 'woocommerce_add_to_cart_fragments', 'blogpro_wcom_cart_fragments' );

/* ---------------------------------------------------------------
 * 7. Form fields — Tailwind classes via the WC field-args filter
 *
 *    Stock WC markup wraps every checkout field in <p class="form-row">
 *    and stamps .input-text / .country_select / .input-checkbox onto the
 *    inputs. We keep those classes (WC core + plugins target them) and
 *    ADD Tailwind utility classes so the input/label/select get the
 *    same look as the rest of the theme.
 * ------------------------------------------------------------- */
function blogpro_wcom_form_field_args( $args, $key, $value ) {
    $input_base = 'block w-full rounded-lg border border-gray-200 bg-white px-3.5 py-2.5 text-sm text-gray-900 shadow-sm placeholder:text-gray-400 focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 focus:outline-none transition-colors';
    $select     = $input_base; // native arrow kept — select2 replaces country/state anyway
    $label      = 'block text-sm font-medium text-gray-700 mb-1.5';

    if ( ! is_array( $args['class'] ) )       $args['class']       = (array) $args['class'];
    if ( ! is_array( $args['label_class'] ) ) $args['label_class'] = (array) $args['label_class'];
    if ( ! is_array( $args['input_class'] ) ) $args['input_class'] = (array) $args['input_class'];

    switch ( $args['type'] ) {
        case 'country':
        case 'state':
            $args['input_class'][] = $select;
            break;
        case 'textarea':
            $args['input_class'][] = $input_base;
            break;
        case 'checkbox':
            // The label IS the wrapper for checkboxes — flex layout only.
            $args['label_class'][] = 'flex items-start gap-2 text-sm text-gray-700 cursor-pointer select-none';
            $args['input_class'][] = 'mt-0.5 h-4 w-4 rounded border-gray-300 text-indigo-600 focus:ring-indigo-500';
            break;
        case 'select':
            $args['input_class'][] = $select;
            break;
        default:
            // text, tel, email, password, number …
            $args['input_class'][] = $input_base;
            break;
    }

    // Wrap-row class — kept as form-row (plugins + select2) but styled
    // as a vertical stack with consistent spacing.
    $args['class'][] = 'blogpro-field-row block mb-4';
    if ( 'checkbox' !== $args['type'] ) {
        $args['label_class'][] = $label;
    }

    return $args;
}
add_filter( 'woocommerce_form_field_args', 'blogpro_wcom_form_field_args', 10, 3 );

/* ---------------------------------------------------------------
 * 8. Quantity inputs — Tailwind classes on the stock <input class="qty">
 *    and the wrapping <div class="quantity">.
 * ------------------------------------------------------------- */
function blogpro_wcom_qty_classes( $classes ) {
    // Stock: input-text qty text — keep them, add Tailwind.
    $classes[] = 'block w-20 rounded-lg border border-gray-200 bg-white px-3 py-2 text-sm text-center text-gray-900 shadow-sm focus:border-indigo-500 focus:ring-2 focus:ring-indigo-200 focus:outline-none';
    return array_values( array_unique( $classes ) );
}
add_filter( 'woocommerce_quantity_input_classes', 'blogpro_wcom_qty_classes' );

/* ---------------------------------------------------------------
 * 9. "Proceed to checkout" button — match Tailwind's primary button
 *    without forking the proceed-to-checkout-button template.
 * ------------------------------------------------------------- */
function blogpro_wcom_order_button_html( $html ) {
    $primary = 'inline-flex w-full items-center justify-center gap-2 rounded-lg bg-indigo-600 px-6 py-3.5 text-base font-semibold text-white shadow-sm transition-colors hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-indigo-500 focus:ring-offset-2';
    return preg_replace( '/class="([^"]*button[^"]*)"/i', 'class="$1 ' . $primary . '"', $html );
}
add_filter( 'woocommerce_order_button_html', 'blogpro_wcom_order_button_html' );

/* ---------------------------------------------------------------
 * 10. Place-order button (in checkout/payment.php) — same treatment.
 * ------------------------------------------------------------- */
add_filter( 'woocommerce_pay_order_button_html', 'blogpro_wcom_order_button_html' );

/* Proceed-to-checkout anchor in cart/cart.php carries a different class
 * ("checkout-button button alt wc-forward") — we override the template
 * at /woocommerce/cart/proceed-to-checkout-button.php so the markup
 * uses Tailwind directly, no string surgery on stock HTML. */

/* ---------------------------------------------------------------
 * 11. Cart page buttons (update cart / apply coupon) are styled
 *     directly in the /woocommerce/cart/cart.php template override.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 12. Product loop start/end — the /woocommerce/loop/loop-start.php
 *     + loop-end.php template overrides replace the stock
 *     <ul class="products"> with the same 1→2→3→4 col Tailwind grid
 *     /shop/ uses, so related / up-sell / cross-sell sections match.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 13. Payment-method radios — handled by the /woocommerce/checkout/
 *     payment-method.php template override (<li> gets Tailwind classes
 *     directly there; no string surgery on stock HTML needed).
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 14. Star-rating widget — stock HTML uses a fixed-width <span> over
 *     a star background. Re-render as inline SVG so it scales with
 *     Tailwind text size, and matches the indigo accent elsewhere.
 * ------------------------------------------------------------- */
function blogpro_wcom_get_rating_html( $html, $rating, $count ) {
    if ( 0 >= $rating ) return $html;

    $rating = max( 0, min( 5, (float) $rating ) );
    $pct    = ( $rating / 5 ) * 100;

    $stars = '';
    for ( $i = 1; $i <= 5; $i++ ) {
        $fill = $rating >= $i ? 'text-amber-400' : ( $rating >= $i - 0.5 ? 'text-amber-300' : 'text-gray-200' );
        $stars .= '<svg class="w-4 h-4 ' . $fill . '" fill="currentColor" viewBox="0 0 20 20" aria-hidden="true"><path d="M9.049 2.927c.3-.921 1.603-.921 1.902 0l1.286 3.957a1 1 0 00.95.69h4.162c.969 0 1.371 1.24.588 1.81l-3.367 2.446a1 1 0 00-.364 1.118l1.287 3.957c.299.921-.756 1.688-1.539 1.118l-3.366-2.446a1 1 0 00-1.176 0l-3.367 2.446c-.782.57-1.838-.197-1.539-1.118l1.287-3.957a1 1 0 00-.364-1.118L2.05 9.384c-.783-.57-.38-1.81.588-1.81h4.162a1 1 0 00.95-.69l1.299-3.957z"/></svg>';
    }

    /* translators: %s: rating */
    $label = sprintf( esc_html__( 'Rated %s out of 5', 'woocommerce' ), $rating );
    $count_html = $count
        ? ' <span class="text-xs text-gray-500">(' . intval( $count ) . ')</span>'
        : '';

    return '<span class="inline-flex items-center gap-0.5" role="img" aria-label="' . esc_attr( $label ) . '" title="' . esc_attr( $label ) . '">' . $stars . $count_html . '</span>';
}
add_filter( 'woocommerce_product_get_rating_html', 'blogpro_wcom_get_rating_html', 10, 3 );

/* ---------------------------------------------------------------
 * 15. Stock product-loop image — single_add_to_cart etc. emit a <img>
 *     directly via $_product->get_image(). The media-optimize whole-
 *     page buffer pass rewrites it to /blogpro-img/. No filter needed.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 16. Stock single-product gallery — wc_get_gallery_image_html builds
 *     a <div class="woocommerce-product-gallery__image"><a><img></a>
 *     </div>. The img is rewritten to WebP by the buffer pass; the
 *     outer <div> + <a> get a class boost via the filter so the
 *     flexslider / zoom / photoswipe JS (which targets those classes)
 *     keeps working AND the markup looks themed.
 * ------------------------------------------------------------- */
function blogpro_wcom_gallery_image_html( $html, $attachment_id = 0 ) {
    // WC's templates fire this filter with 2 args only; the main image
    // is identifiable by the .wp-post-image class on its <img>.
    if ( false !== strpos( $html, 'wp-post-image' ) ) {
        $html = str_replace(
            'class="woocommerce-product-gallery__image"',
            'class="woocommerce-product-gallery__image block overflow-hidden rounded-2xl bg-white"',
            $html
        );
        $html = str_replace( 'class="wp-post-image"', 'class="wp-post-image w-full h-auto object-cover"', $html );
    } else {
        $html = str_replace(
            'class="woocommerce-product-gallery__image"',
            'class="woocommerce-product-gallery__image rounded-lg overflow-hidden border border-gray-100"',
            $html
        );
    }
    return $html;
}
add_filter( 'woocommerce_single_product_image_thumbnail_html', 'blogpro_wcom_gallery_image_html', 10, 2 );

/* ---------------------------------------------------------------
 * 17. Product tabs (description / reviews / additional) — the
 *     /woocommerce/single-product/tabs/tabs.php template override
 *     emits Tailwind pill styling on the <ul class="tabs wc-tabs">.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 18. Stock "in stock" / "out of stock" badges — Tailwind classes
 *     live in the /woocommerce/single-product/stock.php override.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 19. Order notes textarea + create-account checkbox on checkout.
 *     The textarea inherits .input-text from form_field_args above;
 *     the create-account field is built inline in form-billing.php
 *     (we override that template), so no global filter needed.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 20. Empty cart / order received — handled via templates below.
 * ------------------------------------------------------------- */

/* ---------------------------------------------------------------
 * 21. Store-specific CSS that Tailwind utilities cannot express —
 *     the responsive <table> → stacked-card pattern for the cart /
 *     checkout tables and the WC select2 dropdown sizing. WC's own
 *     stylesheet was dequeued above presumably leaving these tables
 *     unscaled on phones, so this is the whole replacement.
 * ------------------------------------------------------------- */
function blogpro_wcom_inline_css() {
	$css = '
	@media (max-width: 767px) {
		.woocommerce table.shop_table_responsive thead { display: none; }
		.woocommerce table.shop_table_responsive tbody tr td {
			display: block;
			text-align: right !important;
			clear: both;
			padding-left: 45%;
			min-height: 2.5rem;
		}
		.woocommerce table.shop_table_responsive tbody tr td.product-name { text-align: left !important; padding-left: 0; }
		.woocommerce table.shop_table_responsive tbody tr td::before {
			content: attr(data-title);
			float: left;
			font-weight: 500;
			color: #4b5563;
		}
		.woocommerce table.shop_table_responsive tbody tr td.actions::before { content: none; }
		.woocommerce table.shop_table_responsive tbody tr td.actions { text-align: left !important; padding-left: 0; }
		.woocommerce table.shop_table_responsive tbody tr td {
			border-top: 1px solid #f3f4f6;
		}
		.woocommerce table.shop_table_responsive.wc-shipping-totals tbody tr td::before { float: none; display: block; }
	}
	.select2-container--default .select2-selection--single {
		height: 42px;
		border-radius: 0.5rem;
		border-color: #e5e7eb;
	}
	.select2-container--default .select2-selection--single .select2-selection__rendered { line-height: 40px; color: #111827; }
	.select2-container--default .select2-selection--single .select2-selection__arrow { height: 40px; }
	.woocommerce-checkout-review-order-table tbody td.product-thumbnail { width: 80px; }
	';
	// wp_add_inline_style nests the CSS before the </style> tag of the handle.
	if ( wp_style_is( 'blogpro-tailwind', 'enqueued' ) || wp_style_is( 'blogpro-tailwind', 'registered' ) ) {
		wp_add_inline_style( 'blogpro-tailwind', $css );
	}
}
add_action( 'wp_enqueue_scripts', 'blogpro_wcom_inline_css', 20 );
